version: '3.8'

services:
  service-registry:
    build: 
      context: ../../
      dockerfile: infrastructure/service-registry/Dockerfile
      args:
        - PACKAGE_PATH=infrastructure/service-registry
    ports:
      - "${EXTERNAL_PORT:-3002}:${PORT:-3000}"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - PORT=${PORT:-3000}
      - REGISTRY_REFRESH_INTERVAL=${REGISTRY_REFRESH_INTERVAL:-30000}
      - SERVICE_TTL=${SERVICE_TTL:-60000}
      - LOG_LEVEL=${LOG_LEVEL:-info}
    volumes:
      - ./src:/app/infrastructure/service-registry/src
      - ../../common:/app/common
    healthcheck:
      test: ["CMD", "wget", "-q", "-O-", "http://localhost:${PORT:-3000}/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s 
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.3'